[tools."http:lmstudio"]
url = "https://installers.lmstudio.ai/linux/x64/{{version}}/LM-Studio-{{version}}-x64.AppImage"
version_list_url = "https://versions-prod.lmstudio.ai/update/linux/x86"
version_expr = '[fromJSON(body).version + "-" + fromJSON(body).build]'
version = "latest"
bin = "lmstudio"
